# Secrets for pulling an image from a private repository
imagePullSecrets: []
# Override the chart name.
nameOverride: ""
fullnameOverride: ""

image:
  registry: docker.io
  repository: lbohdan93/go_webapp
  # Overrides the image tag whose default is the chart version
  tag: ""
  pullPolicy: IfNotPresent

# environment
prod: true

# Set Kubernetes Labels to a Pod.
podLabels:
  app: internal-service

podSecurityContext: 
  runAsUser: 1009
  runAsGroup: 1009
  fsGroup: 1009

securityContext: 
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL

# when autoscalling enabled replicaCount
# will be ignored
replicaCount: 3

service:
  type: ClusterIP
  port: 8080
  nodePort: ""

extraEnvs: []
  # - name: "HTTP_PORT"
  #   value: "9000"
  # - name: "FOO"
  #   value: "BAR"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Setup liveness and readiness probes
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Enable autoscalling
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 80

affinity:
  enabled: true
  type: required
