apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: internal-service
  namespace: platform
spec:
  interval: 1m0s
  install:
    disableWait: true
  releaseName: internal-service
  chart:
    spec:
      chart: internal-service
      sourceRef:
        kind: HelmRepository
        name: internal-service-repo
        namespace: platform
  timeout: 30m0s