apiVersion: v1
kind: Service
metadata:
  name: {{ include "internal-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "internal-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "internal-service.httpPort" . }}
      protocol: TCP
      name: http
    {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort)}}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    {{- include "internal-service.selectorLabels" . | nindent 4 }}
