apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: internal-service 
  namespace: platform
spec:
  chart:
    spec:
      version: 0.4.1
  values:
    prod: false
    podLabels:
      app: internal-service-dev
