apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform
resources:
  - ../base/internal-service
patches:
  - path: helm-values.yaml
    target:
      name: internal-service
      kind: HelmRelease